BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[User] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Email] NVARCHAR(1000) NOT NULL,
    [Name] NVARCHAR(1000),
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [User_CreatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [UpdatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [User_pkey] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [User_Email_key] UNIQUE NONCLUSTERED ([Email])
);

-- CreateTable
CREATE TABLE [dbo].[Post] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Title] NVARCHAR(1000) NOT NULL,
    [Content] NVARCHAR(1000) NOT NULL,
    [ShortDescription] NVARCHAR(1000) NOT NULL,
    [UrlHandle] NVARCHAR(1000) NOT NULL,
    [IsVisible] BIT NOT NULL CONSTRAINT [Post_IsVisible_df] DEFAULT 1,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [Post_CreatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [UpdatedAt] DATETIME2 NOT NULL,
    [AuthorId] INT NOT NULL,
    [CategoryId] INT,
    CONSTRAINT [Post_pkey] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [Post_UrlHandle_key] UNIQUE NONCLUSTERED ([UrlHandle])
);

-- CreateTable
CREATE TABLE [dbo].[Category] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Name] NVARCHAR(1000) NOT NULL,
    [UrlHandle] NVARCHAR(1000) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [Category_CreatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [UpdatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Category_pkey] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [Category_UrlHandle_key] UNIQUE NONCLUSTERED ([UrlHandle])
);

-- AddForeignKey
ALTER TABLE [dbo].[Post] ADD CONSTRAINT [Post_AuthorId_fkey] FOREIGN KEY ([AuthorId]) REFERENCES [dbo].[User]([Id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[Post] ADD CONSTRAINT [Post_CategoryId_fkey] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Category]([Id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
